version: "3.8"

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: moviedb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persistent storage
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    command: --init-file /docker-entrypoint-initdb.d/init.sql  # Ensures `init.sql` runs on every start
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5


  application:
    build: ./application
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=moviedb
    volumes:
      - ./application:/application
      - ./ml-latest-small:/application/ml-latest-small  # Mount dataset inside container
    networks:
      - app_network



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  # Access phpMyAdmin at http://localhost:8080
    environment:
      PMA_HOST: database        # This should match your MySQL service name
      PMA_USER: root
      PMA_PASSWORD: example
    depends_on:
      - database
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
